In [101]:
import pandas as pd
import numpy as np

### Question 1

What's the version of Pandas that you installed?

You can get the version information using the `__version__` field:

In [2]:
pd.__version__


'2.0.3'

### Question 2

How many columns are in the dataset?

- 10



In [62]:
dataset = pd.read_csv("./housing.csv")
ncol = dataset.shape[1]
print(f'the dataset has {ncol} columns')


the dataset has 10 columns



### Question 3

Which columns in the dataset have missing values?

- `total_bedrooms`



In [64]:
dataset.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64


### Question 4

How many unique values does the `ocean_proximity` column have?

- 5


In [65]:
dataset.nunique()

longitude               844
latitude                862
housing_median_age       52
total_rooms            5926
total_bedrooms         1923
population             3888
households             1815
median_income         12928
median_house_value     3842
ocean_proximity           5
dtype: int64


### Question 5

What's the average value of the `median_house_value` for the houses located near the bay?

- 259212



In [70]:
dataset.ocean_proximity.drop_duplicates()

0         NEAR BAY
701      <1H OCEAN
954         INLAND
1850    NEAR OCEAN
8314        ISLAND
Name: ocean_proximity, dtype: object

In [72]:
dataset.query('ocean_proximity=="NEAR BAY"')['median_house_value'].describe().round(0)

count      2290.0
mean     259212.0
std      122819.0
min       22500.0
25%      162500.0
50%      233800.0
75%      345700.0
max      500001.0
Name: median_house_value, dtype: float64


### Question 6

1. Calculate the average of `total_bedrooms` column in the dataset.
2. Use the `fillna` method to fill the missing values in `total_bedrooms` with the mean value from the previous step.
3. Now, calculate the average of `total_bedrooms` again.
4. Has it changed?

Has it changed?

> Hint: take into account only 3 digits after the decimal point.

- No


In [88]:
ave_total_bedrooms = dataset['total_bedrooms'].mean()
ave_total_bedrooms.round(3)

537.871

In [89]:
dataset.total_bedrooms.fillna(ave_total_bedrooms).mean().round(3)

537.871


### Question 7

1. Select all the options located on islands.
2. Select only columns `housing_median_age`, `total_rooms`, `total_bedrooms`.
3. Get the underlying NumPy array. Let's call it `X`.
4. Compute matrix-matrix multiplication between the transpose of `X` and `X`. To get the transpose, use `X.T`. Let's call the result `XTX`.
5. Compute the inverse of `XTX`.
6. Create an array `y` with values `[950, 1300, 800, 1000, 1300]`.
7. Multiply the inverse of `XTX` with the transpose of `X`, and then multiply the result by `y`. Call the result `w`.
8. What's the value of the last element of `w`?

> **Note**: You just implemented linear regression. We'll talk about it in the next lesson.

- -1.4812
- 0.001
- 5.6992
- 23.1233






In [90]:
dataset['ocean_proximity'] = dataset['ocean_proximity'].str.strip().str.replace(' ','_')

In [91]:
dataset['ocean_proximity'].drop_duplicates()

0         NEAR_BAY
701      <1H_OCEAN
954         INLAND
1850    NEAR_OCEAN
8314        ISLAND
Name: ocean_proximity, dtype: object

In [95]:
X = dataset.query('ocean_proximity=="ISLAND"')[['housing_median_age', 'total_rooms', 'total_bedrooms']].values
X

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

In [99]:
XTX = X.T.dot(X)
XTX


array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [106]:
XTXinv = np.linalg.inv(XTX)
XTXinv

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

In [108]:
y = np.array([950, 1300, 800, 1000, 1300])

In [113]:
XTXinvXT = XTXinv.dot(X.T)
w = XTXinvXT.dot(y)
w

array([23.12330961, -1.48124183,  5.69922946])

In [114]:
print(f'Value of the last element of w is {w[-1]:.4f}')

Value of the last element of w is 5.6992
